### ISSUE TITLE
Main source directory src not marked as source directory

### ISSUE THREAD

**Issue by dudanov** [edvin/tornadofx-idea-plugin#1]
After created new project with plugin, main source directory /src/main/kotlin not marked as Source Directory. Version of IDE: 2016.1.2

**Comment by edvin** [comment]
Confirmed! Will get right on it, thanks :)

**Comment by edvin** [comment]
I've uploaded a new version of the plugin (1.0.2) - will you give it a try?

**Comment by edvin** [comment]
Hmm.. I'm having some mixed results while I test here. There might be an issue, so I'll continue to look, but please let me know what you find.

**Comment by dudanov** [comment]
Thanks! It's work!

**Comment by edvin** [comment]
Perfect, I'll close the issue. Thanks again for reporting this and please let me know if there are any more features you'd like to see in this plugin.
