### ISSUE TITLE
IDEA plugin installed but `import tornadofx.*` fails

### ISSUE THREAD

**Issue by texadactyl** [edvin/tornadofx-idea-plugin#101]

**Comment by texadactyl** [comment]
Environment: 
- Xubuntu 18.04.up-to-date.
- IntelliJ IDEA 2019.1.3 (Community Edition)
- Build #IC-191.7479.19, built on May 28, 2019
- JRE: 1.8.0_202-release-1483-b58 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Linux 4.15.0-5

4-generic

Yesterday, I installed the latest IntelliJ IDEA and the TornadoFX plugin through IDEA.  I created a new project for kotlin/JVM. I expected that the plugin would be installed such that the required jars were in the build path but apparently not so.  

Is there a manual step that I missed that makes tornadofx available for importing to projects?

![xx](https://user-images.githubusercontent.com/11318756/61303749-a6bb8a00-a7ad-11e9-8e6f-dcbfe06c5750.png)

**Comment by texadactyl** [comment]
I forgot to mention that I did add TornadoFX to the project library path and restarted IDEA before attempting to build/rebuild the project.

![xx](https://user-images.githubusercontent.com/11318756/61305891-40d10180-a7b1-11e9-9122-ebe12be9a80a.png)

**Comment by edvin** [comment]
You don’t need to add the plugin to the classpath, you need to add the TornadoFX jar and dependencies :) I suggest you make a new project based on the Maven or Gradle templates if you are unsure of how to add a library with your build system.

**Comment by texadactyl** [comment]
I was doing this out of order.  I should have started my project with TornedoFX (not kotlin/JVM)
and selected tornadofx-maven-plugin. Then, add JavaFX JARs as global libraries.
Then, build.  All good up to this point.

Now, I can try and execute.
