### ISSUE TITLE
tornado-maven-project Failed to run

### ISSUE THREAD

**Issue by luke-finlayson** [edvin/tornadofx-idea-plugin#103]
Sorry, this might be a bit of a silly problem but I'm having issues trying to get the tornado-maven-project template to run after created a project with it. I keep getting this string of errors:
![Annotation 2020-03-04 135328](https://user-images.githubusercontent.com/30330558/75834026-bf051580-5e1f-11ea-9fb0-ccf22508088a.png)

**Comment by luke-finlayson** [comment]
Still not sure what the issue was, but I am now running it on Linux and it works just fine.

**Comment by edvin** [comment]
I believe you were running Java 13 against TornadoFX 1.7, which only supports Java 8 :)
