### ISSUE TITLE
When will the new version be published

### ISSUE THREAD

**Issue by stars-one** [edvin/tornadofx-idea-plugin#104]
Hope publish a new version soon~

**Comment by stars-one** [comment]
a new version for the 1.7.20 of tornadofx

**Comment by edvin** [comment]
TornadoFX 1.7.20 was released on Jan 31st. There are few changes to the code base since that release. Are you waiting for something specific?

**Comment by stars-one** [comment]
well,I look forward to the new feature,like onLeftClick and onRightClick,and can easily loading the media resource,and others feature

Looking forward to your new version

**Comment by SchweinchenFuntik** [comment]
@Stars-One Could you please clarify what exactly you want. I have not yet understood what exactly is meant by "onLeftClick and onRightClick" and "and can easily loading the media resource".

Or is it about a library, not a plugin.

**Comment by stars-one** [comment]
> @Stars-One Could you please clarify what exactly you want. I have not yet understood what exactly is meant by "onLeftClick and onRightClick" and "and can easily loading the media resource".
> 
> Or is it about a library, not a plugin.

@SchweinchenFuntik 
I see.I am worried that something wrong in the old plugin when I update the version  of tornadofx.

**Comment by SchweinchenFuntik** [comment]
radically new features have not been added
