### ISSUE TITLE
[Bug] Fail to import/run the tornadofx-gradle-project in the IDEA 2020.1

### ISSUE THREAD

**Issue by floating-cat** [edvin/tornadofx-idea-plugin#107]
I try to create the tornadofx-gradle-project in the IDEA 2020.1, but I unable to import/run it.
It seems the template project uses the Gradle 4.4, which is not supported well in the new IDEA version.

And because a bug in the IDEA: https://youtrack.jetbrains.com/issue/IDEA-231576, it will swallow the error messages when importing this project.

I tried to update the Gradle version and the Kotlin version in this template, and it helps.

**Comment by SchweinchenFuntik** [comment]
fix #112
