### ISSUE TITLE
create ItemViewModel 

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx-idea-plugin#11]
The plugin already creates a `viewModel`. Would be nice if it can create an ItemViewModel too

**Comment by edvin** [comment]
Absolutely. When it auto creates a ViewModel from a model object there really is no reason to not use `ItemViewModel` by default, so I will just swap it for that.

**Comment by edvin** [comment]
Fixed, so that this `Customer` object:

``` kotlin
class Customer(id: Int, name: String) {
    var id by property<Int>(id)
    fun idProperty() = getProperty(Customer::id)

    var name by property<String>(name)
    fun nameProperty() = getProperty(Customer::name)
}
```

Will result in the following `CustomerModel`:

``` kotlin
class CustomerModel : ItemViewModel<Customer>() {
    val id = bind { item?.idProperty() }
    val name = bind { item?.nameProperty() }
}
```

Using the `ItemViewModel` you no longer need to deal with rebinding, because it is automatically done for you when the `item` value or the `itemProperty.value` are assigned a new value.
