### ISSUE TITLE
Run/Debug Configurations cannot be added

### ISSUE THREAD

**Issue by olk90** [edvin/tornadofx-idea-plugin#114]
Hi, after the latest update of IntelliJ CE it seems no longer possible to add new run configs from the TornadoFX template which appears completely blank (s. screenshot). Also all old configs were deleted and are no longer available.

![image](https://user-images.githubusercontent.com/68084339/95132905-c4816000-0760-11eb-946a-020b87a3189f.png)

Here some system details:

* OS: Manjaro Linux with kernel 5.4
* IntelliJ 2020.2.2 (CE)
* Plugin version 1.7.20

## Edit

IntelliJ 2020.2.3 is affected as well.

I have tried a complete reinstall and changed the kernel version back to 4.19, but the plugin is still not working.

**Comment by olk90** [comment]
I have noticed some strange behavior on the machine, so I've decided to reinstall the operating system. After setting up IntelliJ again the plugin works just fine. So, this issue might be related to messed up OS.

**Comment by DiXL0f0S** [comment]
Same after updating to Intellij idea 2020.3
Windows 10
[Exception log.txt](https://github.com/edvin/tornadofx-idea-plugin/files/5651166/Exception.log.txt)
