### ISSUE TITLE
Using the plugin in 2020.3 fetch an old version: 

### ISSUE THREAD

**Issue by Jonatha1983** [edvin/tornadofx-idea-plugin#116]
![image](https://user-images.githubusercontent.com/3816566/103214872-58a33380-491a-11eb-883a-83d9ae42c742.png)

**Comment by elliotcm** [comment]
That explains why my brand new project in a brand new intellij install didn't work.

Looks like the current version of the plugin is configured to allow installation on 2020.2 only.

If you install the jetbrains "toolbox app" you can use it to manage installs of multiple versions (or do it manually).

<img width="1109" alt="Screenshot 2020-12-28 at 20 51 31" src="https://user-images.githubusercontent.com/109225/103243521-0bdb4f00-4952-11eb-9208-616bb995700a.png">
