### ISSUE TITLE
NoDescriptorForDeclarationException in 2020.3.1

### ISSUE THREAD

**Issue by Creeperface01** [edvin/tornadofx-idea-plugin#118]
Code checking is not working properly after this error occurrs
https://pastebin.ubuntu.com/p/3nYQS2DztX/

**Comment by SchweinchenFuntik** [comment]
Please enter your plugin version. I noticed that an old version is installed on IDEA 2020.3.x

**Comment by SchweinchenFuntik** [comment]
Check if the bug is reproducible in the new version. And if there are mistakes then reopen
