### ISSUE TITLE
Some classes I can't find in [InjectCompomentAction.kt],Cannot import

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx-idea-plugin#16]
![image](https://cloud.githubusercontent.com/assets/22107668/21881999/8e7ae01c-d8e3-11e6-8be8-a093bbb4db4b.png)

**Comment by edvin** [comment]
Are you trying to setup the project to work on the code for the plugin? I think your IDEA doesn't have the correct version of the IDEA Kotlin plugin installed, so you can't find those classes.

**Comment by QingMings** [comment]
I'm using IDEA 2016.3

I'm sure I installed kotlin plugin.
![image](https://cloud.githubusercontent.com/assets/22107668/21883439/169e0d4c-d8ea-11e6-9048-d5b445491a34.png)

**Comment by edvin** [comment]
You have to add the kotlin plugin jar to the dependencies for your project. You have to manually browse for it inside the IDEA program folder. For example, on my machine, it's in:

`C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\plugins\Kotlin\lib\kotlin-plugin.jar`

**Comment by QingMings** [comment]
Yes, that's fine, thank you :)

**Comment by edvin** [comment]
Good! Let me know if you have any issues getting the plugin to run locally or if have have any questions about how it all ties together.
