### ISSUE TITLE
intellaj tornadofx gradle plugin creates incorrect source trees

### ISSUE THREAD

**Issue by DALDEI** [edvin/tornadofx-idea-plugin#17]
Using gradle 3.3, Intellij 16.1 
New Project TornadoFX -> tornadofx_gradle
I get a completely blank workspace/project.
After a few tries (same)  I look at the filesystem and it has

<projectname>/root0/
<projectname>/root1/kotlin/...

root0 contains a close to buildable project,  root1 contains a copy of root0/src/main/kotlin

```

|-- root0
|   |-- build.gradle
|   |-- gradle
|   |   `-- wrapper
|   |       |-- gradle-wrapper.jar
|   |       `-- gradle-wrapper.properties
|   |-- gradlew
|   |-- gradlew.bat
|   |-- src
|   |   `-- main
|   |       `-- kotlin
|   |           `-- com
|   |               `-- example
|   |                   `-- demo
|   |                       |-- app
|   |                       |   |-- MyApp.kt
|   |                       |   `-- Styles.kt
|   |                       `-- view
|   |                           `-- MainView.kt
|   `-- TestView.kt
`-- root1
    `-- kotlin
        `-- com
            `-- example
                `-- demo
                    |-- app
                    |   |-- MyApp.kt
                    |   `-- Styles.kt
                    `-- view
                        `-- MainView.kt

```

cd root0
gradle build
error: 'mainClassName not found'   (close)

the application plugin needs 

mainClassName = 'com.ecample.demo.app.MyApp'

After that change, 
gradle build 
gradle run

works

restart intellij and open "root0" as the project -- ready to go

**Comment by edvin** [comment]
I'm going to remove the old project templates and generate a new project wizard that let's you choose buld system etc, and generate the project structure instead of relying on these templates. There are some issues with the template parsing for gradle build files, so I'l divert resources to the project wizard instead of trying to solve this :)
