### ISSUE TITLE
Please change build.gradle to avoid "Invalid signature file digest for Manifest main attributes" errors

### ISSUE THREAD

**Issue by josephhu** [edvin/tornadofx-idea-plugin#18]
After I included [Microsoft's JDBC drivers](https://blogs.msdn.microsoft.com/jdbcteam/2016/11/17/open-source-jdbc-maven/) in my project, I got the error **"Invalid signature file digest for Manifest main attributes"** whenever I ran the jar file generated.
To fix this problem, please consider changing the build.gradle file from
```gradle
jar {
    manifest {
        ...
    }
    from configurations.compile.collect { entry -> zipTree(entry) }
}
```
to
```gradle
jar {
    manifest {
        ...
    }
    from (configurations.compile.collect { entry -> zipTree(entry) }) {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
}
```

**Comment by edvin** [comment]
Thank you, and sorry for the late reply. I've changed the default gradle build file to include these excludes. However, I will soon rewrite the whole template part of the plugin to provide better gradle support. We have an issue with IDEA parsing the build file and adding escape characters as well.
