### ISSUE TITLE
Don't enable plugin by default. Use 'Add Framework Support...' instead

### ISSUE THREAD

**Issue by hlibkoval** [edvin/tornadofx-idea-plugin#21]
Now plugin is enabled by default in every Kotlin project, even without tornadofx dependencies on classpath or whatever, which litters Intention Actions menu in projects that do not use tornadofx, but only vanilla Kotlin.

Suggestion is to use 'Add Framework Support...' module menu and dialog to manage and enable plugin to prevent littering in non-tornadofx projects.

**Comment by edvin** [comment]
Good catch, I will look into this.

**Comment by edvin** [comment]
I finally figured out how to add a Facet and discriminate the intentions based on facet availability. I'm looking into facet auto detection, and will release a new version of the plugin shortly :)

**Comment by edvin** [comment]
This is live in plugin version 1.7.6 :)
