### ISSUE TITLE
Convert all properties to Tornadofx Properties not working 

### ISSUE THREAD

**Issue by toplinuxsir** [edvin/tornadofx-idea-plugin#23]
Convert all properties to Tornadofx Properties not working ,
It only convert the first property ,not all property
Any idea? Thanks !

**Comment by edvin** [comment]
Hi! Thanks for reporting :) This bug was actually fixed a while ago, I'll release a new version of the plugin shortly, after we've tested it a little better. ETA this weekend :)

**Comment by edvin** [comment]
Version 1.7.6 of the plugin was just released with this fix :) Let me know if it doesn't solve the issue for you. Be aware that you must now install the TornadoFX facet to enable the intentions, but the plugin should automatically detect the need for and install the facet.

**Comment by toplinuxsir** [comment]
Yes it works ,Thanks !
