### ISSUE TITLE
projectTemplate   version is wrong

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx-idea-plugin#24]
Today ,I updated my tornadofx idea plugin  to  1.7.6 version . when I create a new Project .
I found the  tornadofx framework version is 1.6.2, and kotlin version is 1.0.6 
I download the projecttemplate from this repository, and decompression it , The same problem。
mabey You uploaded it wrong。

**Comment by edvin** [comment]
Hi! Thanks for reporting. I just noticed myself this morning, will release a new version of the plugin later today with new templates.

**Comment by QingMings** [comment]
Thanks!

**Comment by edvin** [comment]
Plugin version 1.7.7 is out with this fix :)
