### ISSUE TITLE
Gradle import doesn't respect kotlin compiler existing settings or settings in the build file

### ISSUE THREAD

**Issue by kastork** [edvin/tornadofx-idea-plugin#27]
Every time you refresh a project from a gradle build, the Kotlin module in project settings compiler configuration reverts to Java 1.6.  Also, if you have "use project settings checked" it becomes unchecked.

This may be a kotlin plugin problem rather than a tornadofx plugin problem.  Also, it is possible the problem lies with the gradle integration directly.  But we need to start somewhere, right?

**Comment by edvin** [comment]
I would think we just need to add the gradle specific way of describing Java 8 source/target for IDEA to stop messing with the compiler settings. Something like:

```gradle
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

**Comment by kastork** [comment]
I already do that typically.

![image](https://user-images.githubusercontent.com/202288/27284150-5b7a11c0-54ac-11e7-9109-56081fac9590.png)

It is the JVM target that keeps getting reset.  Also, the checkmark to "Use Project Settings" is unchecked whenever you sync up also.

![image](https://user-images.githubusercontent.com/202288/27284215-a424294c-54ac-11e7-88f6-fb95488f33a5.png)

But what is odd is that the test settings stick.

![image](https://user-images.githubusercontent.com/202288/27284238-b51c5bd4-54ac-11e7-9d77-02b7316178fb.png)

More and more convinced this is Kotlin plugin, not TornadoFX plugin.

**Comment by kastork** [comment]
Looks like a known issue

https://youtrack.jetbrains.com/issue/KT-17492
