### ISSUE TITLE
Use New Root Syntax

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx-idea-plugin#3]
Currently this plugin will generate a given `View` like so: 

``` kotlin
class MyView : View() {
    override val root = BorderPane()

    init {

    }
}
```

We probably should update it to use the new `root` syntax.

``` kotlin
class MyView : View() {
    override val root = borderpane { 
    }
}
```

**Comment by edvin** [comment]
Great, will get right on it! This is actually not a small undertaking, because I need to identify that we have a builder for the root type the user selects. If so we can use the builder syntax, if not we must use the old.

**Comment by edvin** [comment]
Version 1.5.4.2 of the plugin has been released with this functionality :)
