### ISSUE TITLE
Add the ability to easily extract string literals to resource bundles

### ISSUE THREAD

**Issue by txxwzfiv** [edvin/tornadofx-idea-plugin#35]
**Description**
Currently it is rather flow breaking to have to switch between a TornadoFX Component and a resource bundle if one wants to write a internationalization aware application.
Given that TornadoFX supports [Internationalization](https://edvin.gitbooks.io/tornadofx-guide/content/17.%20Internationalization.html), it would be a nice addition for the plugin to have the ability to extract hard-coded Strings to a suitable Resource Bundle.

**Use case**
1. User has a hard-coded string
2. User invokes the intention action
3. User selects the "Extract hard-coded String to $ComponentFileName Resource Bundle"
4. Plugin creates the $ComponentFileName Resource Bundle if it doesn't exist
5. Plugin shows a popup window containing two textboxes:
- Property name (auto generated based on the value of the string on which the action was invoked)
- Property value (value of the string on which the action was invoked)
6. The values are written to the file
7. Replaces the string with a suitable messages["$propertyName"]

**Result**
- Automates the busywork of having to switch and manually add the strings to resource bundles.

**Comment by edvin** [comment]
Good thinking! It might also need to ask for what language to create the properties file for.

**Comment by SiebelsTim** [comment]
#66
