### ISSUE TITLE
Example don't work

### ISSUE THREAD

**Issue by vertexpipeline** [edvin/tornadofx-idea-plugin#37]
![image](https://user-images.githubusercontent.com/26230414/29264187-bb5367e0-80e4-11e7-88f1-0afc8db6cbac.png)
Sample TornadoFX project from new project window doesn't work. Also when I add some new library such as `kotlinx-coroutines-core`, gradle throws `kotlin not configured` message(on screen). Configure kotlin in Tools can't help to solve it.

**Comment by vertexpipeline** [comment]
And how to i can build artifact from gradle? I've tried to build via JavaFX pref, but didn't compile any .jar, only .class files.

**Comment by vertexpipeline** [comment]
Oh, ToradoFX well works with Maven, recent problem is a problem with Gradle plugin. Thanks

**Comment by edvin** [comment]
I just tried it with Gradle and it worked good for me. You do have to answer some questions that appear in popups once the project is loaded, to remove the old modules and add the new detected modules. There seem to be some issues with your classpath as well. Can you zip the project and upload it here so I can take a look at what's going on?

**Comment by vertexpipeline** [comment]
sorry, i've replaced gradle with maven(

**Comment by edvin** [comment]
Good choice IMO :)

**Comment by vertexpipeline** [comment]
oh, i've new issue

**Comment by vertexpipeline** [comment]
![image](https://user-images.githubusercontent.com/26230414/29308051-fdee82a6-81ac-11e7-9052-7454ec65a39f.png)
