### ISSUE TITLE
Feature: Show color in the gutter for color values

### ISSUE THREAD

**Issue by anidotnet** [edvin/tornadofx-idea-plugin#43]
It would be nice to show color in the gutter against color values in css dsl code, just like what raw css plugin does.

![image](https://user-images.githubusercontent.com/696662/30469294-2177f126-9a0d-11e7-8783-3f63d0774bd5.png)

**Comment by edvin** [comment]
We actually already have that, but it currently doesn't support all color properties, only background I think. Isn't that right @nimakro ?

**Comment by nimakro** [comment]
@anidotnet Thank's for the reminder I actually planned to support all color properties already a while ago,  just didn't get around to do so.  I am pretty swamped with work right now but I will try to fix this asp. Will report back as soon as it is fixed probably next Week.

**Comment by anidotnet** [comment]
@nimakro any update on it yet please?

**Comment by nimakro** [comment]
Hey @anidotnet sorry for the delay, I just have way too much to do at the moment. Anyways I looked into the code and started implementing this feature, it's almost done and I should be finished tomorrow.

**Comment by nimakro** [comment]
This should be resolved with #44. @anidotnet This should be available in the next plugin release.

**Comment by anidotnet** [comment]
Thanks a lot @nimakro and @edvin. Now the obvious question is what is the ETA of the release please?

**Comment by edvin** [comment]
@anidotnet We'll release early next week :)

**Comment by anidotnet** [comment]
@nimakro still could not see colors in the gutter

![image](https://user-images.githubusercontent.com/696662/32332141-b9430b08-c00a-11e7-837d-4e50cf2c3ad9.png)

@edvin could you please reopen the issue?

**Comment by anidotnet** [comment]
It looks like color value only inside a StyleSheet class is supported. Can we extend that to any class please? Also, is it possible to add support for derived color value as well?
