### ISSUE TITLE
The Gradle project template should use the Gradle Wrapper

### ISSUE THREAD

**Issue by ItsHarper** [edvin/tornadofx-idea-plugin#48]
The Gradle Wrapper is the recommended way of using Gradle, so it'd be nice if we didn't have to set it up ourselves.

**Comment by edvin** [comment]
The reason for this is that the Project Template functionality in IDEA will mangle the gradle wrapper script when it duplicates it for a new project, so we decided to remove it until IDEA is fixed :)

I reported the bug to JetBrains a while back:

https://youtrack.jetbrains.com/issue/IDEA-166037

**Comment by ItsHarper** [comment]
Ah, ok. Is it mangling the line endings for the bat script on windows or something? 

Edit: nevermind, that's what I get for responding via email. 

---- On Sun, 26 Nov 2017 06:45:21 -0500 notifications@github.com wrote ----

The reason for this is that the Project Template functionality in IDEA will mangle the gradle wrapper script, so we decided to remove it until IDEA is fixed :)

**Comment by edvin** [comment]
I think it incorrectly escaped # and possibly other characters :)
