### ISSUE TITLE
Generating Properties for Primary Constructor

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx-idea-plugin#5]
I don't know if this is something you want to pursue, Edvin, since I'm not sure of the effort/value ratio. 

I'm documenting the rest of the plugin chapter in the guide. I noticed to generate TornadoFX properties off plain properties, you have to put the properties in the class body. 

![image](https://cloud.githubusercontent.com/assets/7420801/18226929/aca67cba-71da-11e6-8043-9fd22fbfb7c6.png)

There does not seem to be that option when the properties are in the primary constructor. 

![image](https://cloud.githubusercontent.com/assets/7420801/18226937/d652a62e-71da-11e6-8995-62e7cdaa84d1.png)

Is this an easy fix?

**Comment by edvin** [comment]
This should absolutely be possible to fix :) I'll get to it after we have landed the next release :)

**Comment by edvin** [comment]
Fixed and uploaded test version to slack. Let me know when you have tested. I'll release a new version of the plugin when you're happy with it :)

**Comment by thomasnield** [comment]
Beautiful, nice work! This is now resolved as well.

**Comment by thomasnield** [comment]
I will update the documentation tonight now that both of these fixes are in. This plugin has become very useful and time-saving.
