### ISSUE TITLE
Build runs with gradle, but does not with TornadoFx run configuration

### ISSUE THREAD

**Issue by IARI** [edvin/tornadofx-idea-plugin#50]
I get this error when trying to run my TornadoFx project:
![image](https://user-images.githubusercontent.com/1053417/34915818-b7b0f11e-f92c-11e7-974d-eb59468f4dd9.png)

Running the build with gradle works just finde.
Is the plugin not using Gradle?

**Comment by edvin** [comment]
I tried with the latest IDEA, latest plugin and everything seems fine. Make sure you're running IDEA with the 1.2.10 Kotlin plugin. If you're already on the latest version, try attaching the generated project to this issue and I'll look at it.

I don't know what you mean by "Is the plugin not using Gradle"?

**Comment by IARI** [comment]
I am using a newer Version of the Kotlin plugin. 

I had to sort out some issues but for now the build process works fine for me with gradle.
What confuses me is the fact, that it runs fine when I launch the application via the gradle 'run' task, but fails with the TornadoFX Idea plugin run-config

**Comment by edvin** [comment]
I will try to compile against the latest Kotlin plugin and see if that helps :)

**Comment by IARI** [comment]
By now I updated to kotlin 1.2.30.
Here's an excerpt of my buildscript:

```
buildscript {
    ext.kotlin_version = '1.2.30'
    ext.kotlin_sdtlib_version = '1.2.30'
    ext.serialization_version = '0.4.2'

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://dl.bintray.com/kotlin/kotlinx" }
        maven { url "http://dl.bintray.com/kotlin/kotlin-eap" }
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
    }
}

apply plugin: "antlr"
apply plugin: "kotlin"
apply plugin: 'kotlinx-serialization'
apply plugin: "application"
```
and further down in dependencies there is
```
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_sdtlib_version"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
    compile 'no.tornado:tornadofx:1.7.15'

```
Still facing the same issue.

**Comment by edvin** [comment]
What version of IDEA are you running? Could you post a complete project that exhibits this issue?

**Comment by IARI** [comment]
Using 2017.2.7:
![image](https://user-images.githubusercontent.com/1053417/37372957-f7e1f3b2-2714-11e8-87ea-76fa97854cf0.png)

You can download the Project here from [google drive](https://drive.google.com/open?id=1akbMYDLVes2xTkSIPNDGquAFwI50lL_E).

But I have to apologize in advance: its a private project, i don't have time to clean anything, so its a huuuge mess, with lots of dependencies and code is an utter chaos ... but im hoping that gradle does all its magic ..

**Comment by edvin** [comment]
I think it's best if you create a standalone sample app with minimal code but that still showcases the issue. That way we can rule out anything not related to the plugin.

**Comment by IARI** [comment]
Don't know if it's relevant to the issue (maybe its a separate thing) but everytime after I create a gradle-based idea project using the tornadofx plugin, when i try to build this happens:
![image](https://user-images.githubusercontent.com/1053417/37373617-9901538a-2717-11e8-9221-3f9b89bd067b.png)

![image](https://user-images.githubusercontent.com/1053417/37373633-ae095cdc-2717-11e8-99b0-781dbd956ea3.png)

![image](https://user-images.githubusercontent.com/1053417/37373718-12090e76-2718-11e8-92d9-605440df65a7.png)

 I have to reopen the project a few times and reimport the gradle config and sometimes idea seems to have forgotten the tornadofx plugin association ...

![image](https://user-images.githubusercontent.com/1053417/37373761-4bbe4b18-2718-11e8-8c25-682c7f464732.png)

before finally things work.
Now here is the [minimal project](https://drive.google.com/open?id=1Lm9qrZuNivd4KNxSs-zHPO3HoIH8t94G) - its basically just the start project, but with the added gradle dependency for the kotlinx-serialization.

The build works with a run config that just executes the "run" gradle task.
![image](https://user-images.githubusercontent.com/1053417/37374061-abd17740-2719-11e8-9878-a359ba32fc29.png)

but fails with a run config based on the plugin:
![image](https://user-images.githubusercontent.com/1053417/37374071-b8dfcf18-2719-11e8-9de3-690be459cccf.png)

same issue:
![image](https://user-images.githubusercontent.com/1053417/37374077-bfd1f378-2719-11e8-8b01-5074be3fb884.png)

**Comment by SiebelsTim** [comment]
This looks like this https://github.com/Kotlin/kotlinx.serialization/issues/87

Feel free to correct me, and we'll reopen the ticket.
