### ISSUE TITLE
Can't create any TornadoFX run configuration

### ISSUE THREAD

**Issue by sefholt** [edvin/tornadofx-idea-plugin#53]
**Intellij IDEA**
> IntelliJ IDEA 2017.3.2 (Ultimate Edition)
> Build #IU-173.4127.27, built on December 25, 2017
> JRE: 1.8.0_152-release-1024-b8 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.6

**TornadoFX Plugin** 
> 1.7.14

**TornadoFX Library**
> compile 'no.tornado:tornadofx:1.7.14'

What I tried?

1. Create default Gradle project
I created empty project as follows:
![2018-02-01 0 51 21](https://user-images.githubusercontent.com/4698222/35649571-982d28aa-06ea-11e8-86d2-9b2406b89eaa.png)
Then tried to add new TornadoFx run configuration:
![2018-02-01 1 01 52](https://user-images.githubusercontent.com/4698222/35649970-acb744bc-06eb-11e8-8f76-b87715e514bf.png)

2. Create project from TornadoFX templates
I created `tornadofx-gradle-project` with Gradle settings like in my first attempt. Then tried to create new run configuration:
![2018-02-01 1 05 28](https://user-images.githubusercontent.com/4698222/35650183-61b71e78-06ec-11e8-8568-a4d2d5352bea.png)

In both cases there's no way to pick class extending `tornadofx.App()` as app class. I also tried to select other modules in _Use class path of a module_ chooser (%Module%, %Module%_main).

Moreover I already have an old TornadoFX project with run configurations that worked until recently. Unfortunately I did not notice when and why they stopped working.

**Comment by edvin** [comment]
I think there might be some issues with API changes in the Kotlin Plugin. I compiled locally against 2017.3.3 and the included plugin there and now it works. I'll release a new plugin version shortly.

**Comment by edvin** [comment]
A new plugin version has been released. Let me know if this solves the issue for you :)

**Comment by sefholt** [comment]
Thanks for the quick response!
Unfortunately I'm still not able to create configuration using chooser dialog, but I can just _type_ fully qualified app class name. That works perfectly even in 1.7.14. So I can see no difference between 1.7.14 and 1.7.14.1.
By the way automatic detection does not work too:
![2018-02-01 14 11 39](https://user-images.githubusercontent.com/4698222/35675891-cd6a98de-075a-11e8-9b18-cf971490813a.png)

**Comment by SiebelsTim** [comment]
Looks like the `TreeClassChooserFactory` always creates `TreeJavaClassChooserDialog`s which don't work with kotlin classes.

**Comment by edvin** [comment]
Can we subclass it and fix? I haven't looked at the code myself yet.

**Comment by SiebelsTim** [comment]
The ClassBrowser depends in the java interface. So it probably needs a little bit more fiddling than that, but it's nothing impossible
