### ISSUE TITLE
Potential improvements to template gradle project

### ISSUE THREAD

**Issue by ze** [edvin/tornadofx-idea-plugin#59]
The [build.gradle](https://github.com/edvin/tornadofx-idea-plugin/blob/master/template-projects/tornadofx-gradle-project/build.gradle) for the template gradle project can be updated and improved in ways.

We can update the Kotlin version to `1.2.41` and the TornadoFX version to `1.7.16`. I recommend creating some variable `ext.tornadofx_version = "1.7.16"` so that we can update the version at the top of the file rather than scroll down to our dependencies and update there.

Also, the variable `mainClassName` can be plugged into this [line](https://github.com/edvin/tornadofx-idea-plugin/blob/605cbed61acc1ccaead87b63d124616a0620d91d/template-projects/tornadofx-gradle-project/build.gradle#L40) to use it.

We can also choose to use JUnit 5 over 4, which I recommend we do, due to the better features JUnit 5 offers, especially with Kotlin.

I'm rusty with the Intellij Platform SDK, but I know there are ways to create runnable configurations, specifically `gradle run` to run the application (and others if need be).

I can submit a pull request if you agree with these potential changes.

**Comment by edvin** [comment]
Absolutely, please do :)
