### ISSUE TITLE
Intent for TableView column generation is not present?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx-idea-plugin#6]
Hey @edvin, I'm not getting any intent to generate columns for the `TableView` in the TornadoFX plugin, as shown in [your webcast](https://www.youtube.com/watch?v=11rcRnJw76s). What exactly do I do to trigger that popup? It's the last thing I think I need to document for Chapter 13 in the TornadoFX Guide.

![image](https://cloud.githubusercontent.com/assets/7420801/18259023/3cb6c64a-73a5-11e6-893d-95d9343418bd.png)

**Comment by edvin** [comment]
This function needed an update to support the new builder syntax. I will attach a version of the plugin that should handle this. Can you check if it works for you before I deploy it?

**Comment by edvin** [comment]
I uploaded it to the Slack channel since GitHub says "Unfortunately, we don't support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP" (I tried ZIP)

**Comment by thomasnield** [comment]
Works now, thank you!
