### ISSUE TITLE
Find missing translations

### ISSUE THREAD

**Issue by SiebelsTim** [edvin/tornadofx-idea-plugin#65]
i.e. a warning when there is no key "myTranslation" for code like this: `messages["myTranslation"]`

This might need an index for the translations. One can also think of code folding into the translation like android studio does.

**Comment by edvin** [comment]
This could be easily fixed by changing the `handleGetObject` function in `FXPropertyResourceBundle`. Do you want to supply a PR perhaps?

**Comment by SiebelsTim** [comment]
I'm not sure if I understand you correctly. I thought about adding a warning to the Intellij plugin. I think you think of adding it to the tornadofx project, which might also make sense in some way. However, the latter will only find (or log?) it when invoked.

I like the current behaviour of `handleGetObject` displaying the key in brackets. Logging a warning to console however might be worth doing though.

**Comment by edvin** [comment]
Aha, I see. Sure, that would be a cool feature in the plugin as well, but I don't have time to prioritize it I'm afraid :)

**Comment by nimakro** [comment]
@SiebelsTim are you planning on sending a PR, if so I will assign the issue to you ;-)

**Comment by SiebelsTim** [comment]
I have no idea when I'm able to tackle this, but I look forward to working on this :)

**Comment by edvin** [comment]
Fantastic! Good luck :))

**Comment by nimakro** [comment]
As far as I am concerned this was implemented with PR #69 (right @SiebelsTim if so can you please close this issue)?

**Comment by SiebelsTim** [comment]
No it isn't. I implemented code folding. The lint/quickfix is still on the list. However, the PR contains an index which is needed for this.
Basically the logic is already there. The lint warning not yet.
