### ISSUE TITLE
Option to convert to TornadoFX property using new syntax

### ISSUE THREAD

**Issue by ruckustboom** [edvin/tornadofx-idea-plugin#7]
Would it be possible to add an option to have the "Convert to TornadoFX Property" command use the new property syntax? e.g.

``` kotlin
val idProperty = SimpleIntegerProperty()
val id: Int by idProperty

val nameProperty = SimpleStringProperty()
var name: String? by nameProperty

val birthdayProperty = SimpleObjectProperty<LocalDate>()
var birthday: LocalDate? by birthdayProperty
```

 I'm not sure how difficult it would be as there would have to be checks for the primitive properties and Strings to create `SimplePrimitiveProperty`s, while defaulting to `SimpleObjectProperty<Type>` for the rest, but I tend to prefer the new syntax myself (for the null safety and extra features added to the specific property classes).

**Comment by ruckustboom** [comment]
I think all the use cases that would have to be covered would be:

| Original Type | Property Type | Mutator Type |
| --- | --- | --- |
| Int | SimpleIntegerProperty | Int |
| Int? | SimpleObjectProperty&lt;Int&gt; | Int? |
| Long | SimpleLongProperty | Long |
| Long? | SimpleObjectProperty&lt;Long&gt; | Long? |
| Boolean | SimpleBooleanProperty | Boolean |
| Boolean? | SimpleObjectProperty&lt;Boolean&gt; | Boolean? |
| Float | SimpleFloatrProperty | Float |
| Float? | SimpleObjectProperty&lt;Float&gt; | Float? |
| Double | SimpleDoubleProperty | Double |
| Double? | SimpleObjectProperty&lt;Double&gt; | Double? |
| String | SimpleStringProperty | String? |
| String? | SimpleStringProperty | String? |
| T | SimpleObjectProperty&lt;T&gt; | T? |
| T? | SimpleObjectProperty&lt;T&gt; | T? |

**Comment by ruckustboom** [comment]
It would also be nice if, when converting a constructor parameter, you have the option of keeping the passed in value as a default.

``` kotlin
class Person(val name: String)
```

becomes

``` kotlin
class Person(name: String) {
    val nameProperty = SimpleStringProperty(name)
    var name: String? by nameProperty
}
```

**Comment by edvin** [comment]
Absolutely, I will add this as a configuration option for the plugin :)

**Comment by edvin** [comment]
Implemented, will roll it out today, but would prefer it you have a few minutes to go over it first @t-boom
