### ISSUE TITLE
Do not extend ApplicationConfigurationType

### ISSUE THREAD

**Issue by develar** [edvin/tornadofx-idea-plugin#77]
I am from JetBrains.

Please do not extend ApplicationConfigurationType. Instead, please use ConfigurationTypeBase.
ApplicationConfigurationType will be final in 2019.1.

**Comment by edvin** [comment]
Thank you, we'll make sure to fix that!

**Comment by SiebelsTim** [comment]
Oh, it was the *Type*. This wasn't depending on a newer version. The `TornadoFXConfiguration` depends on a newer IDEA version.

https://github.com/edvin/tornadofx-idea-plugin/blob/master/src/main/kotlin/no/tornado/tornadofx/idea/configurations/TornadoFXConfiguration.kt

**Comment by edvin** [comment]
I guess it's completely fine to depend on 2018.1 anyways. Are we ready for release?

**Comment by SiebelsTim** [comment]
I don't have anything on the roadmap anymore. So yes, I guess :)

**Comment by edvin** [comment]
Done :)
