### ISSUE TITLE
Option to generate wrapper JavaFX class and/or ViewModel?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx-idea-plugin#8]
Hey @edvin, maybe this is somewhat niche but I use this pattern A LOT. Perhaps it's not worth effort but thought I'd throw this out there. 

I often have two versions of a type: an immutable POKO (plain old Kotlin object), and a TornadoFX version with mutable JavaFX properties.

For instance, here is a simple immutable domain type. 

``` kotlin
class Client(val id: Int, val name: String)
```

It would be cool if I could right-click it and generate a mutable JavaFX `StagedClient` version of it, with the immutable `Client` backing the default values. 

``` kotlin
class StagedClient(client: Client) {
    var name by property(client.name)
    fun nameProperty() = getProperty(StagedClient::name)

    var id by property(client.id)
    fun idProperty() = getProperty(StagedClient::id)
}
```

What do you think? Is this too niche or would more people find value in this?

**Comment by edvin** [comment]
That would certainly be possible, and maybe not so much work either. I don't know how generally useful this will be though, but let me give it a try to see how much work it would be.

I think a more common use case is creating a ViewModel based on a Model object. I suspect that would have a broader appeal, but I can certainly see your use case as well. This proxy object might as well have a function to create an immutable version again, right?

**Comment by thomasnield** [comment]
That would be cool with the `ViewModel` as well, and you're right that might have more universal appeal. I don't see a huge need to create the immutable version from the proxy (at least for my needs), but if you want to add that it can't hurt.

**Comment by thomasnield** [comment]
I think having a small library of patterns that can be generated would make this plugin an enormous value-adding tool.

**Comment by thomasnield** [comment]
I think having a small library of patterns that can be generated would make this plugin an enormous value-adding tool.

I know this is starting to overlap with the `ViewModel`, but perhaps an optional `reset()` function can be added to the generated proxy class as well?

```
class StagedClient(client: Client) {
    var name by property(client.name)
    fun nameProperty() = getProperty(StagedClient::name)

    var id by property(client.id)
    fun idProperty() = getProperty(StagedClient::id) 

   fun reset() { 
       name = client.name
       id = client.id
   }
}
```

**Comment by ruckustboom** [comment]
I don't really see how this is super useful if the `Client` has only immutable fields. What would be the purpose of updating the `StagedClient`? Would a new `Client` have to be created with each update?

I can see the benefit of, say, creating a wrapper class that creates a property for each `var` in the class (and possibly a read-only property for each `val`). In that case, you could create a `ViewModel` for the wrapper that would handle logic like reset and validation.

One potential downside with this is that the properties generated are nullable, so the non-nullable `Int` and `String` in `Client` would have issues without validation, so it would pretty much need a `ViewModel` anyway.

**Comment by thomasnield** [comment]
@t-boom maybe I'm clinging to immutability principles a bit too much, but this is what I use it for: I have many immutable domain types  that are not used in a UI context. They are consumed by algorithms and processes that have no reason to change the properties (much less need the overhead of JavaFX properties).

 But sometimes users need to adjust these parameters and in that case, they are presented in a mutable TornadoFX proxy. When the fields are changed in the proxy, it is compared to the original mutable type and generates the appropriate SQL to the database. The modified items are then re-queried and rebuilt. It may sound like a lot of work but its pretty trivial to do with Kotlin and Rx. The tedious part is creating the proxy wrapper around the immutable type. 

Does that make sense? Or is this a very niche thing I do?

**Comment by thomasnield** [comment]
Did not think of the nullable problem... I see your point there. If you guys want to put this generation towards the `ViewModel`, I'm okay with that. But if its not hard to do both... that would be awesome!

**Comment by ruckustboom** [comment]
It makes sense, it's just not the way I would do it :) But I'm not so vain as to think my was is the only way (or even the correct way)

**Comment by edvin** [comment]
I think we can make this a general purpose ViewModel generator and still cater for Thomas's use case, I will give it a try.

**Comment by thomasnield** [comment]
Haha, no worries you are not being "that guy", and I'm trying not to be either.  

I structure a lot of my framework in strict UI / non-UI layers, mostly because the non-UI layer is very algorithm intensive and needs to be lean with my modest hardware. But here's another case: let's say you simply do not own a given mutable/immutable type, but you want to quickly create a TornadoFX wrapper around it? Especially in this scenario, I do like your idea of relaying changes to mutable `var` properties on the backing type. 

Maybe I'm just weird and being totally unconventional, but I can imagine a couple of cases where the wrapper would make sense. If not, you guys are more than welcome to shoot this down.

**Comment by thomasnield** [comment]
@edvin okay awesome! I do agree `ViewModel` should be priority.

**Comment by edvin** [comment]
Would it be any downside to solving your use case within the ViewModel btw?

**Comment by ruckustboom** [comment]
It could complicate the `ViewModel` since its properties wouldn't actually have a backing property anymore. It would make rolling back and committing quite complicated.

**Comment by edvin** [comment]
What if I detect immutable types and simply wrap those suckers in a `SimpleObjectProperty`? Updating them would do no harm anyways.

**Comment by ruckustboom** [comment]
@thomasnield It's definitely a valid use case, especially if you don't own the model.

**Comment by edvin** [comment]
``` kotlin
class ClientViewModel(client: Client) : ViewModel() {
    val id = bind { SimpleObjectProperty(client.id) }
    val name = bind { SimpleObjectProperty(client.name) }

    fun generateClient() = Client(id.value, name.value)
}
```

**Comment by thomasnield** [comment]
That's what I'm pondering right now. I may not understand the `ViewModel` enough... but it expects all properties to be an `ObservableValue` correct? In that case, I still need to convert the immutable type to a proxy for it. And even if it can be given an immutable type to work with, does it provide a means to redefine what `commit()` does (like write to a database?).

**Comment by edvin** [comment]
Look at my example above. I'm "detecting" that `client.id` and `client.name` are immutable properties, and wrapping them in `SimpleObjectProperty` instances. Commit would still work, and there would be a convenience function to create a new client based on the value in the ViewModel (`generateClient()`).

**Comment by edvin** [comment]
If `client.name` was mutable, it would generate this code:

``` kotlin
class ClientViewModel(client: Client) : ViewModel() {
    val id = bind { SimpleObjectProperty(client.id) }
    val name = bind { client.name }

    fun generateClient() = Client(id.value, name.value)
}
```

**Comment by ruckustboom** [comment]
@edvin That doesn't quite fit the use case @thomasnield has where the saving of the `ViewModel` would update the database, and the backing imutable objects would be re-queried automatically. It seems you would need some sort of custom commit action.

**Comment by ruckustboom** [comment]
Also, the `SimpleObjectProperty` wrapper would still have the nullability problem.

**Comment by thomasnield** [comment]
Wait, it does a have a `save()` function, I forgot. Let me play with it, and definitely put all effort towards that. If you find the proxy class generation to be easy then I will definitely use it, because I have types I do not own quite often.

And thanks for hearing me out guys. If I'm being too self-centric on my personal workflows, I apologize.

**Comment by edvin** [comment]
Well, we're not going to create the update db statements, but it could be used like this:

``` kotlin
model.commit {
    val newClient = model.generateClient()
    updateDatabaseBasedOnOldAndNewClient(model.client, newClient)
    model.rebind {
        client = newClient
    }
}
```

We could even reduce this boiler plate I think.

**Comment by edvin** [comment]
Nullability would need to be solved with validators, which would be trivial.

**Comment by ruckustboom** [comment]
Indeed, I didn't think that through. That should work pretty well.

**Comment by edvin** [comment]
Thomas, how exactly does the call interface to `updateDatabaseBasedOnOldAndNewClient` look like?

**Comment by thomasnield** [comment]
I think @t-boom hit both points in the head of what I'm incoherently trying to say. 1) Nullability is a problem 2) A custom commit() implementation is needed. 

I appreciate you guys hearing me out. Sorry if I'm being self-centric on my personal workflows. I was hoping they might have a broader need. 

Let's step back for a moment: maybe the proxy feature should just be an option? Maybe the goal should be to generate a TornadoFX class off an existing class, without modifying the existing class...

**Comment by thomasnield** [comment]
You guys are moving too fast lol, hold on.

**Comment by thomasnield** [comment]
This actually is pretty cool. I think this could work.

**Comment by edvin** [comment]
I just had another sweet idea.. If you bind to an object in a ViewModel, it could have markers so that it would automatically know that the required validator needs to be applied. That would actually be trivial to implement. The code could look like:

``` kotlin
val id = bind { SimpleObjectProperty(client.id) } required()
```

The IDEA action can add that for immutable fields, and when you use this in an input builder it will automatically add the validator:

``` kotlin
text(model.id) // Required validator is applied automatically
```

**Comment by edvin** [comment]
OK, let's give it a try. If this doesn't work out for your use case, no worries - most of the work will be with the "normal" ViewModel case anyways :)

**Comment by thomasnield** [comment]
Excellent, I think this is looking pretty good. Btw, does `ViewModel` apply to a simple editable `TableView`? As in `TableView<ClientModel>`? Do you see that as a valid pattern?

**Comment by edvin** [comment]
Absolutely :)

**Comment by thomasnield** [comment]
Btw absolutely no rush on this, I was just throwing this idea out there for something to use going forward, and to implement whatever you come up would require me to refactor my existing application.

**Comment by edvin** [comment]
Not rushing, but I made some progress :)

https://www.youtube.com/watch?v=CE7SGM_Oa2I

**Comment by edvin** [comment]
@thomasnield About the `reset` function you asked for. Isn't this `rollback` which we have already? :)

What more do we need to satisfy your use case?

**Comment by thomasnield** [comment]
Yes the rollback is perfect

**Comment by edvin** [comment]
The feature is done and live, so I'll close this ticket.
