### ISSUE TITLE
Simpler and reliable setup with gradle wrapper

### ISSUE THREAD

**Issue by jtonic** [edvin/tornadofx-idea-plugin#85]
It is great the tornadofx idea plugin uses gradle (org.jetbrains.intellij plugin)  for project management.
But, in the current implementation the gradle has to be install on the devs/contributors machine, and, in time, this installed gradle can be out of sync amongst them.
**The Gradle wrapper** can be used to mitigate this issue and simplify the project setup in the IDE .

**Comment by edvin** [comment]
Merged :)
