### ISSUE TITLE
"Extract String into resources" does not find properties file in a separate folder hierarchy

### ISSUE THREAD

**Issue by sg26565** [edvin/tornadofx-idea-plugin#88]
For Maven based projects, the default directory layout keeps source code and property files in separate folder hierarchies.

- `src/main/java` or `src/main/kotlin` for (main) source code
- `src/main/resources` for property files and other resources
- `src/test/java` or `src/test/kotlin` for unit tests
- `src/test/resources` for unit test property files and other test resources

If, for example the source code for class `mypackage.Foo` was stored in `src/main/kotlin/mypackage/Foo.kt` and the properties file was stored in `src/main/resources/mypackage/Foo.properties`, the plugin reports "**Cannot find file Foo.properties**", although `messages["my_message"]` would perfectly load the resource bundle and resolve the key **my_message** into a localized string.

The plugin should search of property files in all paths marked as "Resources" or "Test Resources" in addition to "Sources" and "Tests".

Even better, if the plugin would create missing property files on the fly (after asking the user to select a path).

**Comment by SiebelsTim** [comment]
These are all limitations currently. I planned to fix them some time. It's good to keep track of this issue. 

Finding folders that are marked as Resources is more difficult than it sounds, or at least I didn't find a way to do so. I planned to make the Resource path editable, or rather let the user pick a file in the dialog. 

As always, Pull Requests welcome ;-)

**Comment by sg26565** [comment]
I've already forked your project. Once I get used to Gradle, I'll see what I can do.

**Comment by SiebelsTim** [comment]
Sounds great. :) Feel free to join the slack channel if you have questions.

#tornadofx @ https://kotlinlang.slack.com/

**Comment by SiebelsTim** [comment]
I just found out how to get resource roots:

```kotlin
val project: Project // assume you've got the project
val module = TornadoFXFacet.get(project)!!.module
val rootManager = ModuleRootManager.getInstance(module)

rootManager.contentEntries.flatMap{ it.sourceFolders.toList() }.filter { it.rootType is JavaResourceRootType }
```

This returns `List<SourceFolder>` where you can get the path from.

**Comment by edvin** [comment]
Oh snap, that's great, Tim!

**Comment by sg26565** [comment]
see pull request #90 

This could be further improved if the plugin would ask the user if he wants to create a missing properties file and presents a list of matching resource roots.

**Comment by SiebelsTim** [comment]
This is finished I guess
