### ISSUE TITLE
Don't find translate in gloobal file and don't add missing translation

### ISSUE THREAD

**Issue by ByJacob** [edvin/tornadofx-idea-plugin#92]
Hi, plugin don't find key in gloobal properties (Messages.properties). When i click in "Add missing translation" nothing happens

I have tornadofx plugin in version 1.7.17.1 and intelij version 2018.3

**Comment by SiebelsTim** [comment]
Just to make sure I understand this correctly: You have a class called `Messages` and you want to add a translation. You also have a file `Messages.properties` in your resource path. Does the properties file's path match the package of your class?

If possible, can you share the relevant directory structure?

**Comment by ByJacob** [comment]
![image](https://user-images.githubusercontent.com/23155811/49369672-48e0a300-f6f2-11e8-9b0e-4387131cd4e0.png)

It is my directory structure, file when i try use i18n, and messages.properties. Plugin don't see if have translation in Messages.properties file

**Comment by edvin** [comment]
`messages[welcome_message"]` will look in the file `resources/pl/edu/pwr/weka/sipprogram/gui/view/WelcomeView.properties` for your `welcome_message=` line.

**Comment by ByJacob** [comment]
Ok, but in documentation about [i18n](https://github.com/edvin/tornadofx/wiki/i18n) is, if i can generate default global messages file. Should the plugin also review the default file ? And one more thing that the plugin does not create a file with the translation when i click in "Add missing translation"?

![image](https://user-images.githubusercontent.com/23155811/49370299-0b7d1500-f6f4-11e8-9508-b4483b7c88fe.png)

**Comment by edvin** [comment]
The plugin doesn't look in the global messages file yet, but you're right, it should support this. I guess "Add missing translation" could ask if you want to add to the global or local messages file even, or just supply two intensions "Add missing translation to global bundle" along with the existing one.

**Comment by ByJacob** [comment]
Ok, i wait for a improve it^^  And when file don't exist plugin should create it.

**Comment by SiebelsTim** [comment]
~~I didn't even know about the global file :x~~

The translation support is still somewhat limited. I'll make sure to at least document these wishes in form of tickets.

Edit: 
I think there was a misunderstanding. The "global file" is the file without a language suffix. 
Therefore the global file is `resources/pl/edu/pwr/weka/sipprogram/gui/view/WelcomeView.properties` and the file for the english language would be `resources/pl/edu/pwr/weka/sipprogram/gui/view/WelcomeView_en.properties`.  

Tornadofx cannot associate your file  to the correct `Component` if you would have multiple `Component`s with the same name in different packages. Therefore you need the package prefix in your resources.

So this not a bug™.

**Comment by ByJacob** [comment]
> I didn't even know about the global file :x
> 
> The translation support is still somewhat limited. I'll make sure to at least document these wishes in form of tickets.
> 
> Edit:
> I think there was a misunderstanding. The "global file" is the file without a language suffix.
> Therefore the global file is `resources/pl/edu/pwr/weka/sipprogram/gui/view/WelcomeView.properties` and the file for the english language would be `resources/pl/edu/pwr/weka/sipprogram/gui/view/WelcomeView_en.properties`.
> 
> Tornadofx cannot associate your file to the correct `Component` if you would have multiple `Component`s with the same name in different packages. Therefore you need the package prefix in your resources.
> 
> So this not a bug™.

But when don't find language file about component it take global i18n, [look about it](https://github.com/edvin/tornadofx/blob/e6fbdb66052875168749f12e0787e718f546234b/src/main/java/tornadofx/Component.kt#L159)

And i have only one class with this name:
![image](https://user-images.githubusercontent.com/23155811/49688434-41fec980-fb12-11e8-9746-db61df17363e.png)

**Comment by SiebelsTim** [comment]
Oh, it has to be named `Messages.properties`. You are right. Will fix this.

**Comment by Burtan** [comment]
This still does not work?
I have a Messages.properties file on the root of the resources directory and the translation of the app works, but I still get the warning of missing translations.
